### ISSUE TITLE
Allow overwrite function methodNotAllowedHandler

### ISSUE THREAD

**Issue by ivoszz** [pressly/chi#101]
I am just starting to use your project which seems excellent to me, but  got into trouble with hard coded methodNotAllowedHandler function. I have to return JSON object on every error (like in JSON API spec) and I am not able to specify my own response to this error. Or can you suggest any solution to this? Thanks.

**Comment by pkieltyka** [comment]
hey @ivoszz I see, potentially I can put a `MethodNotAllowedHandler http.Handler` on the chi.Mux and let you set it there. That will work but I need to check the interaction with subrouters.

**Comment by pkieltyka** [comment]
@ivoszz I was just checking into this, and it seems the current `methodNotAllowedHandler` just returns 405 with an empty body, so it should be valid to the response of your json handler

**Comment by ivoszz** [comment]
hey @pkieltyka you are right. The body is empty but still marked as text/html and this doesn't solve the problem of JSON api. text/html is hard coded and cannot be changed even when there are  Accept: application/json or application/vnd.api+json in request header. The header Allow is also not generated (and cannot be) which is against the spec:
"The origin server MUST generate an Allow header field in a 405 response containing a list of the target resource's currently supported methods."
The possibility of redefining methodNotAllowedHandler will be sufficient.

**Comment by pkieltyka** [comment]
got it, good points

**Comment by ivoszz** [comment]
I would like to thank you for your effort.

**Comment by pkieltyka** [comment]
:) no prob
