### ISSUE TITLE
Remove github restriction on markdown docs links

### ISSUE THREAD

**Issue by clinta** [pressly/chi#103]
Relative links in markdown work on more places than just github. They work very nicely in our on-premis gitlab installation for example.

Is there any harm in removing this restriction? If that is not desired, could an additional option be added to MarkdownOpts to force link generation?

**Comment by pkieltyka** [comment]
yea definitely we can improve this if is preventing you in gitlab. I can try to remove them as long as everything continues to link up, otherwise we'll have to add an option like you suggested.

**Comment by pkieltyka** [comment]
@clinta can you be specific about what you have in mind to resolve this and whats the issue? id like to resolve/close

**Comment by clinta** [comment]
See PR #106

If you want to close this and continue the discussion in the PR that's fine by me.

**Comment by pkieltyka** [comment]
thanks for the PR @clinta
