### ISSUE TITLE
Type chi.Middleware

### ISSUE THREAD

**Issue by GeertJohan** [pressly/chi#11]
Can we type `func(next chi.Handler) chi.Handler` ?

I use `New..` methods for some middleware to add stuff to them, which results in:
```go
func NewSomethingCtx(stuff *Stuff)  func(next chi.Handler) chi.Handler  {
	return func(next chi.Handler) chi.Handler {
		// stuff can be used here to set something up (should be done once, as mentioned in #10).
		return chi.HandlerFunc(func(ctx context.Context, w http.ResponseWriter, r *http.Request) {
			// stuff can also be used here, on each request.
			// actual middleware.
		})
	}
}
```

If would be nice if we could let `NewSomethingCtx` return a `chi.Middleware`.

**Comment by GeertJohan** [comment]
I'd be happy to provide a PR.

**Comment by utrack** [comment]
:+1:

**Comment by pkieltyka** [comment]
Hey @GeertJohan - a shorthand would be nice, but it would only save a bit of typing.. as so..

```go
func NewSomethingCtx(stuff *Stuff)  chi.Middleware  {
    return chi.Middleware(func(next chi.Handler) chi.Handler {
        // stuff can be used here to set something up (should be done once, as mentioned in #10).
        return chi.HandlerFunc(func(ctx context.Context, w http.ResponseWriter, r *http.Request) {
            // stuff can also be used here, on each request.
            // actual middleware.
        })
    })
}
```

Im not convinced thats much better. Do you see another way? if so, it would be great to see a quick PR for the discussion.

**Comment by GeertJohan** [comment]
I liked it for documentation and readability. However, when trying to implement a quick example I found that it gets messy real quick. Existing `func(next chi.Handler) chi.Handler` must still need be supported and since `router.Use(..)` accepts `interface{}` there can't be any type conversion going on during the call, which means that internally both types must be handled. It's probably not worth the effort without unless doing a breaking change.

**Comment by GeertJohan** [comment]
Didn't mean to close, although this probably can be closed..?

**Comment by pkieltyka** [comment]
I'd like to keep the middleware signature as close to the standard http.Handler middlewares. I'm going to close this ticket, but if you find an elegant approach please submit a PR. Thanks for the feedback!
