### ISSUE TITLE
Not found handler for subrouters

### ISSUE THREAD

**Issue by smacker** [pressly/chi#110]
Consider this example:

```go
func Create() {
  r := chi.NewRouter()
  r.NotFound(notFound) // weird, if you set NotFound after Mount - it won't affect subrouter at all
  r.Mount("/api", protected(authService))
}

func protected() chi.Router {
  r := chi.NewRouter()
  r.Route("/group", func(r chi.Router) {
     ....
  }
  return r
}

func notFound(rw http.ResponseWriter, r *http.Request) {
  rw.Write("my not found")
}
```

Now let's try some urls:
```
/unknown - "my not found"
/api/unknown - "my not found"
/api/group/unknown - "default not found"
```

It's very unexpected behavior for me. There is workaround, I need to set my not-found handler for protected router explicitly too. Maybe on mount it's better to go through all subrouters and set not-found router there? If that's alright, I can make pull request.

**Comment by pkieltyka** [comment]
@smacker a PR would be great, at a minimum it will help understand possible situations better.

**Comment by pkieltyka** [comment]
perhaps write a quick one to hack it, see how you can make it work as you expect, and we can iterate/refine from there

**Comment by smacker** [comment]
Done. Please take a look. If the problem isn't clear from my description - try tests from PR on master branch. Thanks!
