### ISSUE TITLE
small simplification to URLParam

### ISSUE THREAD

**Issue by nhooyr** [pressly/chi#113]
Can't https://github.com/pressly/chi/blob/master/context.go#L50 be simplified to just

```go
// URLParam returns the url parameter from a http.Request object.
func URLParam(r *http.Request, key string) string {
        return URLParamFromCtx(r.Context(), key)
}
```

**Comment by pkieltyka** [comment]
yes, true it definitely can be

**Comment by pkieltyka** [comment]
feel free to submit a PR for this if you like

**Comment by pkieltyka** [comment]
closing as this isn't an issue, but if you want to submit a PR sometime, go for it
