### ISSUE TITLE
Mounting a subpath of an existing path fails

### ISSUE THREAD

**Issue by dbudworth** [pressly/chi#115]
https://github.com/Spark-Networks/chi/blob/master/mux.go#L239
```
	if mx.tree.findPattern(pattern+"*") != nil || mx.tree.findPattern(pattern+"/*") != nil {
		panic(fmt.Sprintf("chi: attempting to Mount() a handler on an existing path, '%s'", pattern))
	}
```

If you mount:
"/foo" and then "/foobar", all is well as "/foobar*" and "/foobar/*" has no matches

but, if you reverse the mapping order:
"/foobar" and then "/foo", the first findPattern "/foo*" finds a match and fails.

Is that "/foo*" match necessary?  It's problematic for me as I must register the longer path in my app first.  (or re-engineer it a fair amount)

**Comment by pkieltyka** [comment]
hey @dbudworth thanks for the report, I've reproduced the issue, I'll fix it by tomm.
