### ISSUE TITLE
http: multiple response.WriteHeader calls due CloseNotify

### ISSUE THREAD

**Issue by umputun** [pressly/chi#117]
Adding CloseNotify middleware causing sometimes "multiple response.WriteHeader calls" warning in normal cases, i.e. request was not canceled by caller, but finished normally.

Probably sometimes https://github.com/pressly/chi/blob/master/middleware/closenotify.go#L32 reached after normal completion? Not sure what the sequence, but I suspect client completed (and disconnected), connection closed and in select it gets `closeNotifyCh`

**Comment by pkieltyka** [comment]
@umputun interesting, I tested this a bunch of times and it was fine. I'll add a test case for this -- however, something to note is that in Go 1.8, this will be standard functionality and won't even be necessary, so I'll probably check for just Go 1.7 and do nothing above that.

**Comment by pkieltyka** [comment]
btw, if other users are having this same issue, please report

**Comment by umputun** [comment]
I think it is really easy to reproduce.

1. Make dummy rest, with a handler sending back anything with custom response code i.e. smth like `render.Status(r, http.StatusBadRequest); render.JSON(....)`
2. Make sure `router.Use(middleware.CloseNotify)` in place 
3. Hit it a few times and you will see the error (warning)

**Comment by november-eleven** [comment]
@pkieltyka I had the same issue while using [hey](https://github.com/rakyll/hey) load generator with `go 1.7.3`.

**Comment by pkieltyka** [comment]
Cool. I'll fix it soon, but once 1.8 hits this middleware won't be necessary and every request will have this behavior.

**Comment by pkieltyka** [comment]
@umputun @november-eleven Im unable to reproduce the bug on 1.7.3 or 1.8b1

I wrote this program https://gist.github.com/pkieltyka/8be94802255ea023cb1cc59327d44670 to try to simulate the bug, but no luck. If you guys can send back a gist with the bug (or even better a test case), I'll be happy to fix it. Here is the start of a test case as well for CloseNotify: https://gist.github.com/pkieltyka/a4bbf38318b321c3dd21504d26c73821 .. which is also passing, however, it may need a custom ResponseWriter and check the writeHeader doesn't happen twice, but still Im unable to trigger the warning.

**Comment by c2h5oh** [comment]
Tested the program above with `ab -c 1000 -n 10000 http://localhost:3333/` on Linux x86_64 with go 1.7rc2 and 1.7.4 - could not replicate the issue.

What OS are you running?

**Comment by pkieltyka** [comment]
btw, I don't think we're simulating the problem correctly, the client needs to close early to trigger the problem. Some browsers will do this on refresh to a request. 

however, even in Chrome which closes a running connection with a refresh, the server's output looks like..

```
"GET http://localhost:3333/ HTTP/1.1" from [::1]:59724 - 200 11B in 2.002588196s
"GET http://localhost:3333/ HTTP/1.1" from [::1]:59724 - [disconnected] 11B in 2.003083784s
"GET http://localhost:3333/ HTTP/1.1" from [::1]:59725 - 200 11B in 2.003003779s
"GET http://localhost:3333/ HTTP/1.1" from [::1]:59725 - 200 11B in 2.0049129s
"GET http://localhost:3333/ HTTP/1.1" from [::1]:59726 - 200 11B in 2.000145561s
"GET http://localhost:3333/ HTTP/1.1" from [::1]:59726 - [disconnected] 11B in 2.004778573s
"GET http://localhost:3333/ HTTP/1.1" from [::1]:59727 - 200 11B in 2.000354583s
"GET http://localhost:3333/ HTTP/1.1" from [::1]:59727 - 200 11B in 2.002733109s
"GET http://localhost:3333/ HTTP/1.1" from [::1]:59727 - [disconnected] 11B in 2.003348645s
"GET http://localhost:3333/ HTTP/1.1" from [::1]:59732 - 200 11B in 2.000938948s
```

**Comment by umputun** [comment]
if you remove middleware.Logger and keep everything else as is you will see these "multiple response.WriteHeader calls". If you add some sleep before - you will get even more of these.

```
func main() {
	r := chi.NewRouter()
	r.Use(middleware.CloseNotify)

	r.Get("/", func(w http.ResponseWriter, r *http.Request) {
		time.Sleep(100*time.Millisecond)
		v := map[string]interface{}{"x": 1}

		render.Status(r, http.StatusBadRequest)
		render.JSON(w, r, v)
	})
	http.ListenAndServe(":3333", r)
}
```

with `ab -n 100 -c 10 127.0.0.1:3333`  i got bunch of of these

**Comment by pkieltyka** [comment]
@umputun no errors on go 1.8b1 with that code and ab command. I'll have someone try it on 1.7 in a minute. What exact go version and OS are you running?

**Comment by umputun** [comment]
@pkieltyka `go version go1.7.4 darwin/amd64` (mac os 10.12.1) and the same version of go in alpine 3.4 (docker container). Both have the same errors

**Comment by pkieltyka** [comment]
interesting. thanks

**Comment by pkieltyka** [comment]
@umputun confirmed on 1.7 on osx it does have this error, but there is no error on 1.8b1

**Comment by VojtechVitek** [comment]
I see, I didn't test this properly without the Logger middleware applied when I was writing this middleware a year ago.

What happens:
When the handler writes some headers and body to the response writer and then the client closes the connection, this middleware tries to write the header again, which is wrong. The Logger middleware used to catch the extra header write (I'm not sure if it still does that after the recent Logger middleware changes) and also prints [disconnected] at https://github.com/pressly/chi/blob/badf07aee0a9a24f6cffe7acb5c76b2a3bcbdf35/middleware/logger.go#L103 based on the status code. 

Let's just remove this line 
https://github.com/pressly/chi/blob/master/middleware/closenotify.go#L32 and also make it `// +build go1.7`, since it won't work properly in go 1.8 anyway since the stdlib started to close the context when client disconnects.
