### ISSUE TITLE
The logger middleware outputs into stderr

### ISSUE THREAD

**Issue by NikosEfthias** [pressly/chi#120]
The logger middleware outputs into stderr what makes really difficult to read real error messages in the log file

**Comment by pkieltyka** [comment]
@NikosEfthias can you explain some more please? 

however, I have just committed 46d56496c539ad41168671a6b6503f0bacb30a78 which will let you set your own middleware.DefaultLogger = etc... and you can change the logger that you pass to it, so you can specify a file or whatever else you like.

cheers, happy NY

**Comment by NikosEfthias** [comment]
@pkieltyka have you added documentation on how to change that ?  because i have no idea what you mean by `middleware.DefaultLogger` should i edit the source code? middleware is unexported keyword

**Comment by pkieltyka** [comment]
@NikosEfthias thats not something to really document, and middleware is a package, not an unexported keyword. 

something like so is what you want..

```go
// from within your program

// adjust the customLogger as you want, to a file or however you want
customLogger := log.New(os.Stdout, "", log.LstdFlags)

middleware.DefaultLogger = middleware.RequestLogger(&middleware.DefaultLogFormatter{logger: customLogger})
```

**Comment by NikosEfthias** [comment]
just one thing that i don't understand is that i checked the source code theres nothing about stderr how come the messages from logger middleware ends up in the stderr stream

**Comment by NikosEfthias** [comment]
the logger in defaultLogger struct is unexported so its impossible to set it should be exported value i guess

**Comment by pkieltyka** [comment]
Sorry, I am not a help centre for all inquires. I wrote chi and I released it for public so others could benefit from it and as well contribute to build it together - but unfortunately I don't have the bandwidth to answer every question, especially this when it's clearly exported: https://github.com/pressly/chi/blob/master/middleware/logger.go#L15

**Comment by pkieltyka** [comment]
@NikosEfthias indeed you are right.

**Comment by NikosEfthias** [comment]
i just capitalized the first letter of logger key in the struct and it works otherwise it gives error because naturally it cannot find such a property of the struct `DefaultLogFormatter` because `logger` is not an exported keyword.
However after the last update i dont need this anymore the problem that was the reason that i made this bug report about was solved by this update .

**Comment by pkieltyka** [comment]
this will fix it: 076deb80de4f344b761681f2afadf708430cfd41

**Comment by NikosEfthias** [comment]
next time for such small things ill open a pr sorry :)

**Comment by pkieltyka** [comment]
all good :) thanks for bringing it to my attention, but yes PRs are definitely welcome too!
