### ISSUE TITLE
Changing context import for Go 1.7+

### ISSUE THREAD

**Issue by robvdl** [pressly/chi#121]
Chi advertises itself as a Go 1.7+ framework that has 0 dependencies, yet it still imports "golang.org/x/net/context" instead of just "context".

This has the side effect of adding all of golang.org/x/net into my vendor directory when it isn't really necessary.

I have tried changing over the imports in Chi to "context" and everything works fine.  Is there any reason this isn't done already? Or is it for Go 1.6 and below support.

Is there a roadmap of changing this over to "context" and dropping older Go versions?

**Comment by pkieltyka** [comment]
Where does it import net/context? You might be on an older version before context was in stdlib

**Comment by robvdl** [comment]
I am on the last stable tag using Glide so v1.0.0 I will try bumping that to v2.0.0rc1 thanks, that's probably it.

**Comment by pkieltyka** [comment]
Yea. Use master, it's very stable
