### ISSUE TITLE
public RequestID generator

### ISSUE THREAD

**Issue by smacker** [pressly/chi#122]
In my project we can start running code not only through http request, but with cli command or just background processes. I want to be able to trace everything that happened in different part of system by unique id with the same format. For http I use RequestID middleware, but there is no public methods which I can use to generate ID. Copy-past of that functions in project will cause different formats in future.
Do you mind to move request id generator to separate package, or just provide public function to generate new key?

**Comment by pkieltyka** [comment]
@smacker I see, so you want these ID's to be consistent between http requests and other actions? yes, I can move https://github.com/pressly/chi/blob/master/middleware/request_id.go#L65 to a public function to generate the next request id, thats okay with me

**Comment by pkieltyka** [comment]
@smacker I've added middleware.NextRequestID() for you :)

**Comment by smacker** [comment]
thank you sir!
