### ISSUE TITLE
HTTP2 requests are not wrapped using fancyWriter

### ISSUE THREAD

**Issue by lclarkmichalek** [pressly/chi#123]
HTTP requests do not implement `http.Hijacker` or `io.ReaderFrom`. This causes them to not be eligible for wrapping in `middleware.fancyWriter`, instead being wrapped in `middleware.flushWriter`, and losing the `http.CloseNotifier` interface. In addition, `middleware.fancyWriter` does not support `http.Pusher` (in the go 1.8 beta), meaning that even if the writers were eligible for `middleware.fancyWriter`, http2 push would not be possible.

The following snippet, adapted from https://gist.github.com/rakyll/eec415977f85d50a493ca8472ba97b68, shows the various interfaces that the http2 response writer implements:

```go
package main

import (
	"io"
	"log"
	"net/http"
)

func main() {
	http.HandleFunc("/", func(w http.ResponseWriter, r *http.Request) {
		_, cn := w.(http.CloseNotifier)
		_, fl := w.(http.Flusher)
		_, hj := w.(http.Hijacker)
		_, rf := w.(io.ReaderFrom)
		_, ps := w.(http.Pusher)

		log.Printf("rw: %T", w)
		log.Printf("cn: %v", cn)
		log.Printf("fl: %v", fl)
		log.Printf("hj: %v", hj)
		log.Printf("rf: %v", rf)
		log.Printf("ps: %v", ps)
	})
	// Run crypto/tls/generate_cert.go to generate cert.pem and key.pem.
	// See https://golang.org/src/crypto/tls/generate_cert.go
	log.Fatal(http.ListenAndServeTLS(":7072", "cert.pem", "key.pem", nil))
}
```

Output (go 1.8beta2, accessing the server using Chrome 55.0.2883.95)

```
2016/12/31 15:06:17 rw: *http.http2responseWriter
2016/12/31 15:06:17 cn: true
2016/12/31 15:06:17 fl: true
2016/12/31 15:06:17 hj: false
2016/12/31 15:06:17 rf: false
2016/12/31 15:06:17 ps: true
```

In terms of resolution, `http.Hijacker` needs to be handled separately, as http2 will not support it: https://github.com/golang/go/issues/14797. I don't know about `io.ReaderFrom` however. 

Given that to allow interfaces to pick and choose as they like, we'd need around 25 different types, it's probably not practical to support every combination of requests. Would having a `middleware.httpFancyWriter` and a `middleware.http2FancyWriter` make sense?

**Comment by lclarkmichalek** [comment]
https://github.com/felixge/httpsnoop/blob/master/wrap.go#L52 although maybe one could just implement all the different combinations..

**Comment by pkieltyka** [comment]
PR's are welcome :)

**Comment by pkieltyka** [comment]
I think http and http2 fancy writers make sense too

**Comment by lclarkmichalek** [comment]
Yeah, I'm really not a fan of that solution, but after spending half an hour writing a thing to generate the 2^5 individual implementations, I've been convinced that its probably the simpler option.

**Comment by pkieltyka** [comment]
@lclarkmichalek yes probably. I'll give it a closer look but I don't know when I'll have a chance to dive in.

**Comment by lclarkmichalek** [comment]
I can get you a pull request this weekend :) Need to submit something
similar to a load of other projects, so not a problem
