### ISSUE TITLE
Could you update to correct semver on releases

### ISSUE THREAD

**Issue by wyaeld** [pressly/chi#132]
I've found that tools like https://github.com/constabulary/gb don't work nicely with your releases because of a semver issue

Basically the problem is http://semver.org/#spec-item-9
A pre-release version MAY be denoted by appending a **hyphen** and a series of dot separated identifiers immediately following the patch version

Point being it needs a hyphen to comply with the spec
`v2.0.0rc1` is not valid, but `v2.0.0-rc1` is.

Would it be too much trouble for you to please push another release with a valid tag?  The old one can still exist to as not to break things for other people.

**Comment by pkieltyka** [comment]
Will do! Thanks for letting me know

**Comment by wyaeld** [comment]
No problem, the rapid response is encouraging for considering using your library :-)

**Comment by VojtechVitek** [comment]
@pkieltyka I think we can release v2.0.0 after HTTP2 fixes.

**Comment by pkieltyka** [comment]
@VojtechVitek yea, I agree. It's been a long time since the rc

**Comment by pkieltyka** [comment]
v2 is here! https://github.com/pressly/chi/releases/tag/v2.0.0
