### ISSUE TITLE
Different return type of middleware

### ISSUE THREAD

**Issue by kevingo** [pressly/chi#138]
Hi, I found some middleware return `func(next http.Handler) http.Handler`, and others return `http.Handler`.  

It means that user have to use different ways to user middleware, for example, for logger middleware, which returns `http.Handler` we use `r.Use(middleware.Logger)`, and for Timeout middleware, which returns `func(next http.Handler) http.Handler`, we have to declare a fn variable and use that fn in middleware.

```go
r.Use(middleware.Logger)
fn := middleware.Timeout(time.Second)
r.Use(fn)
```

Should we make the middleware always return `http.Handler` type ?

**Comment by VojtechVitek** [comment]
1. `func(next http.Handler) http.Handler` is **middleware** type to be used in `r.Use()`
2. `http.Handler` is **handler** type to be used in `r.Get()` etc.

---

What's wrong with
```go
r.Use(middleware.Logger)
r.Use(middleware.Timeout(time.Second))
```
?

**Comment by kevingo** [comment]
@VojtechVitek Thanks for response. I am misunderstanding the returning type and handler type. Thanks again. I will close the issue.
