### ISSUE TITLE
Profiler middleware doesn't work with StripSlashes/RedirectSlashes

### ISSUE THREAD

**Issue by advanderveer** [pressly/chi#142]
Thanks for the awesome router! Got some trouble with combining the slashes middleware with the profiler middleware. As an example doing a middleware stack like this:

```Go
r := chi.NewRouter()
r.Use(middleware.RedirectSlashes)
r.Mount("/debug/", middleware.Profiler())
```

will prevent the profiler path `/debug/pprof/` to keep redirecting. 

Cheers,

Ad

**Comment by pkieltyka** [comment]
Makes sense, I recommend not using them together, based on how the profile sets up its routes. If you must, you can use r.Group() to have a separate middleware chain for a different set of routes along the same point.

**Comment by lrstanley** [comment]
Another solution to this problem is mentioned in the below linked issue, that doesn't require a new stack of middleware to be created:

https://github.com/go-chi/chi/issues/262#issuecomment-1200322044
