### ISSUE TITLE
multiple routes to same function & localization

### ISSUE THREAD

**Issue by dadatawajue** [pressly/chi#145]
Hi, I looked through the examples and tried to explore other projects using Chi but I couldn't find an answer so I figured I would try here.. with Flask it's possible to do:

```
@app.route('/signup')
@app.route('/register')
def register():
```
Is it possible to do something similar with Chi?

It can quickly end up looking like a mess if I continue to do like this:
```
r.Route("/register", func(r chi.Router) {
  r.Get("/", controllers.RegisterGET)
  r.Post("/", controllers.RegisterPOST)
})
r.Route("/signup", func(r chi.Router) {
  r.Get("/", controllers.RegisterGET)
  r.Post("/", controllers.RegisterPOST)
})
```

I was also wondering how everyone was doing localization (example.com/en/register), I figured it would look something like this:
```
r.Route("/:lang/register", func(r chi.Router) {
  r.Get("/", controllers.RegisterGET)
  r.Post("/", controllers.RegisterPOST)
})
```
and then in controllers.GET/POST do
```
func RegisterGET(w http.ResponseWriter, r *http.Request) {
  lang := strings.Trim(r.URL.Path, "//")
  ...
}
```

Is there a better way to achieve this?

**Comment by pkieltyka** [comment]
@dadatawajue for a controllers package / pattern, I think you'd be pleased with: https://github.com/pressly/chi/tree/master/_examples/todos-resource -- check out the approach there. 

As for lang, you could do it as url param like you've done there and reference "lang" from chi.URLParam(r, "lang"), or put the lang on the r.Context() through a middleware. Or use a request header and set lang on request context there.
