### ISSUE TITLE
what is the best way to cache a http request ?

### ISSUE THREAD

**Issue by medyagh** [pressly/chi#147]
if I want to cache the response for at least 2 minutes, so next client gets same response, 
is there a built in feature ? or do I need to add something like reddis?

**Comment by pkieltyka** [comment]
@medyagh chi is just a simple router, you can layer in any technique you'd like. I suggest doing some research on "http caching" and "cache-control"

**Comment by medyagh** [comment]
for the record, I ended up using memached.
