### ISSUE TITLE
question: determine route string from router, url, method

### ISSUE THREAD

**Issue by kpurdon** [pressly/chi#150]
# Problem

I have a need to get the text repr of the route, say: `/foo/:bar/baz` given a `chi.Router` and an `http.Request`.

We've been running on an httprouter fork w/ this functionality:

`_, handledPath, _, _ := rm.Router.LookupRoute(r.Method, r.URL.Path)`

see: https://github.com/jehiah/httprouter/commit/f17f1397d64b8510e22d980c7093c355880358ef

# Question

Is there currently a way to do this with `pressly/chi`, I'm not seeing anything obvious. If no, would you be open to adding this (would be happy to do it myself)?

**Comment by pkieltyka** [comment]
Hey @kpurdon yea definitely something that comes in handy. The support we have is the RoutePattern and RoutePatterns values on the routing context. You'll want to concat the RoutePatterns for the full thing. The only downside with current implementation is we build the pattern as the request passes through the handler chain, so just keep that in mind. 

Btw, what are you using it for? I hope it fits for you

**Comment by kpurdon** [comment]
@pkieltyka thanks for the response, I'll take a look. We (Bitly) are currently doing some prototyping to determine if we want to switch to chi. This specific feature is used in middleware that publishes API request metrics.

Thanks again. I'll report back if this approach doesn't work out for us.

**Comment by pkieltyka** [comment]
yea, exactly, its a good use for metric tracking - we do the same thing at Pressly

**Comment by pkieltyka** [comment]
it would be awesome to have Bitly on board as well :) good luck and I hope it ends up working out

**Comment by pkieltyka** [comment]
btw here is an example middleware

```go
func main() {
	r := chi.NewRouter()

	r.Use(middleware.RequestID)
	r.Use(middleware.Logger)
	r.Use(middleware.Recoverer)
	r.Use(middleware.TrackRoute)

	r.Get("/users", userHandler)

	http.ListenAndServe(":3333", r)
}

func TrackRoute(next http.Handler) http.Handler {
	return http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		next.ServeHTTP(w, r)
		rctx := chi.RouteContext(r.Context())
		routePattern := strings.Join(rctx.RoutePatterns, "")
		fmt.Println("route:", routePattern)
	})
}
```
