### ISSUE TITLE
Make backwards compatible with x/net/context for Go 1.6.x

### ISSUE THREAD

**Issue by sgp** [pressly/chi#151]
This is a time-limited desire, but right now App Engine classic runtime is still based upon 1.6. Not sure when they will make the jump, and it would be awesome to use chi on an App Engine for Golang right now.

I think this could be done with build tags.

Any interest in this at all?

**Comment by pkieltyka** [comment]
sorry, but no. Im very focused on keeping chi very precise and minimal and focusing on the future.

if you want a x/net/context compatible version of chi, check out the v1 branch -- https://github.com/pressly/chi/tree/v1

**Comment by VojtechVitek** [comment]
Sorry, we can't support Go 1.6, since the http.Request doesn't have Context at all.

**Comment by sgp** [comment]
Thanks for weighing in. I'll check out the v1 branch. TBH, by the time I get around to using chi in appengine, it's Go 1.8 will be released and (hopefully) in the default App Engine runtime.

**Comment by pkieltyka** [comment]
yea hopefully they upgrade appengine soon. You could always host somewhere else, then later move to appengine as you're closer to prod
