### ISSUE TITLE
Is it possible to get path/URL by  HandlerFunc?

### ISSUE THREAD

**Issue by Labutin** [pressly/chi#162]
Is it possible to get path/URL by  HandlerFunc?
Like this:

http://flask.pocoo.org/docs/0.12/api/#flask.url_for

**Comment by pkieltyka** [comment]
Like this? https://github.com/pressly/chi/issues/150

**Comment by Labutin** [comment]
No,
I am looking like this:

`func handlerPing(w http.ResponseWriter, _ *http.Request) {
	fmt.Fprint(w, "pong")
}

...

r.Get("/v1/ping", handlerPing)
...


// I am looking this method
url := r.UrlFor(handlerPing) // have to return "/v1/ping"



func (mx *Mux) UrlFor(handlerFn http.HandlerFunc) string {
    ......
}`

**Comment by pkieltyka** [comment]
ah I see. that isn't something supported by chi directly, but I am sure there would be a way for you to built it yourself by enhancing the chi.Router interface.
