### ISSUE TITLE
Is there a way to mount a Server-Sent Event server along side other routes in Chi?

### ISSUE THREAD

**Issue by sivasiva** [pressly/chi#170]
Most SSE implementations I see in the wild are standalone servers that just serve the events at `/` or `http.Handle("/events/", b)`. 

I would like to know if it is possible to mount an [Event Server](https://github.com/kljensen/golang-html5-sse-example/blob/master/server.go) on a route along other Chi routes.

If yes, can you please provide some pointers on how that might be accomplished?

Awesome router btw, thanks for a really neat library.

**Comment by pkieltyka** [comment]
hey @sivasiva - absolute, this would work with chi just as:

```go
r := chi.NewRouter()
r.Handle("/events/", b)
```
