### ISSUE TITLE
Question: Hashtag in URL after Google oAuth callback

### ISSUE THREAD

**Issue by everdev** [pressly/chi#178]
After completing a Google oAuth login, I redirect to the homepage:

`http.Redirect(w, r, "/", http.StatusTemporaryRedirect)`

But I end up with a hashtag in the URL:

`http://127.0.0.1:8080/#`

I can't seem to find where the # is coming from. Is there a way in Chi to remove this from the URL? I tried setting up a route to catch it `r.Get("/#", RedirectToHomePage)`, but the hash still persists in the URL even through multiple redirects, which makes me think it's being added as a result of the request params. Any suggestions?

**Comment by pkieltyka** [comment]
Hey @everdev this is a question for stdlib go, net/http - not really a chi thing.

Check out the Fragment on a url.URL and run some examples on how it works. Fragments/anchors are intended for the client-side and aren't something that are processed on the server-side.
