### ISSUE TITLE
Cannot figure out how to use docgen

### ISSUE THREAD

**Issue by NikosEfthias** [pressly/chi#180]
i go get `...pressly/chi/docgen` but theres no such executable on my `$GOBIN` and cannot figure out how to use that Could be please be a bit more specific about the usage

**Comment by pkieltyka** [comment]
hey @NikosEfthias good question - because of how docgen works, it needs to be compiled with the program that it is generating docs for. As a result, the way to trigger it as a cli flag when starting your server.

like here: https://github.com/pressly/chi/blob/master/_examples/rest/main.go#L99-L109

**Comment by NikosEfthias** [comment]
Ah now it makes sense :) Great ill try now @pkieltyka

**Comment by NikosEfthias** [comment]
@pkieltyka I just tried the docs are really not that helpful I must say. It could be cool if there are comments on the functions those are used for routing, to show those comments as godoc does

**Comment by pkieltyka** [comment]
hey @NikosEfthias - docgen isn't made to replace all of your API documentation. Its more designed today as internal documentation to easily see your routing structure. If someone was willing to put more work into it, it could get better, but personally it's not a priority for me nor do I have the availability.
