### ISSUE TITLE
REST example doens't work.

### ISSUE THREAD

**Issue by MrSpock** [pressly/chi#181]
Hi,
When I'm trying to build example rest service there are a lot of error related to render:
```
# command-line-arguments
./rest.go:77: undefined: render.RenderList
./rest.go:78: undefined: render.Render
./rest.go:91: undefined: render.Render
./rest.go:102: undefined: render.RenderList
./rest.go:109: cannot use r (type *http.Request) as type io.Reader in argument to render.Bind:
	*http.Request does not implement io.Reader (missing Read method)
./rest.go:110: undefined: render.Render
./rest.go:118: undefined: render.Render
./rest.go:328: undefined: render.Renderer
./rest.go:359: undefined: render.Renderer
./rest.go:368: undefined: render.Renderer
./rest.go:118: too many errors
```

**Comment by pkieltyka** [comment]
you must be doing something wrong.

**Comment by pkieltyka** [comment]
check your imports, you're probably importing some other "render" package

**Comment by MrSpock** [comment]
Yeah.
Somehow goimports is imporing other package:
[I] [0] spock@macspock ~/.g/src ➞ find . -name 'render'
./github.com/cweill/gotests/internal/render
./github.com/pressly/chi/render
[I] [0] spock@macspock ~/.g/src ➞

**Comment by Banashek** [comment]
I'm currently facing this exact issue. @MrSpock how did you end up fixing the imports?

**Comment by MrSpock** [comment]
Double check your import statements. My problem was made by VCS editor code completion tool and fact that I had in my $GOPATH two other packages that had render module :)
When go imports was launched on save it add wrong package to imports.

**Comment by Banashek** [comment]
Yeah I'm using VCS and see the same thing when running `find . -name 'render'` as you did. So if the other package is being used in another project, do I just need to delete it while I'm working on this project?

**Comment by MrSpock** [comment]
You don't have to delete any packages. Just add manually proper import statement for chi/render and don't depend  100% on VSC plugin autocompletion for imports.

**Comment by pkieltyka** [comment]
thanks @MrSpock for weighing in and offering the help.

**Comment by Banashek** [comment]
Thanks for the help!
