### ISSUE TITLE
NotFound is ignored for FileServer

### ISSUE THREAD

**Issue by JaCoB1123** [pressly/chi#184]
Using the following code, the NotFound Handler is not used for files that are not found.

```
r := chi.NewRouter()
r.NotFound(func(w http.ResponseWriter, r *http.Request) {
    http.ServeFile(w, r, "static/index.html")
})

workDir, _ := os.Getwd()
filesDir := filepath.Join(workDir, "static")
r.FileServer("/", http.Dir(filesDir))

http.ListenAndServe(":3333", r)
```

**Comment by bgv** [comment]
Chi's FileServer is just a helper around http.FileServer which does the NotFound check internally.

Ideally you should check if the file exists and return the desired error yourself before calling ServeHTTP.

You can check #155 as starting point for your own implementation.

**Comment by JaCoB1123** [comment]
Awesome, thanks. That's all I need.
I may add a PR to extend the FileServer example if that's in your interest.

**Comment by JaCoB1123** [comment]
Just noticed that you mentioned that you aren't interested in a PR in #155. Closing this.
