### ISSUE TITLE
DefaultDecoder misses typical parameters such as charset

### ISSUE THREAD

**Issue by djui** [pressly/chi#185]
I understand that the `DefaultDecoder` is just a best-effort default, but I believe it would be easy to also extend the matching. Currently, example given for JSON, it only matches exactly `application/json` although it is a quit common real-world behaviour to send in an encoding, such as `application/json; charset=utf-8`. 

Certainly one could ask what the behaviour for parsing parameters should be and what the limits are. But without going into too much specialisation, just adding support for `charset=utf-8` seems like a sufficient and easy extension. For anything more specific likely one needs to implement their own decoder anyways, e.g. to support content-type negotiation and versioning.

I suggest to either add `application/json; charset=utf-8` for the JSON case, or let `GetRequestContentType` return the individual type parts (such as `top-level type name / [ tree. ] subtype name [ +suffix ] [ ; parameters ]`) and then only match on the top-level type name for now.

**Comment by pkieltyka** [comment]
you're right @djui - I'll add it to the v3 list

**Comment by dsincl12** [comment]
Haha, just wasted hours on this one with vue-resource and Axios. nothing got to through to the api, postman worked flawlessly :)

**Comment by pkieltyka** [comment]
@djui I just pushed a fix, please let me know if you continue to have issues

**Comment by djui** [comment]
Thanks Peter, that works.

I the meantime I wrote a Content type parser as we started to use vendor namespace resources and there the detecting JSON as suffix (`+json`) requires a bit more parsing than the split.
I also wanted to offer all parts (top-level type, subtype, suffix, and paremters) to the client so they can choose.
