### ISSUE TITLE
Proper way to query URL params?

### ISSUE THREAD

**Issue by dadatawajue** [pressly/chi#186]
I realize this probably belongs at StackOverflow, but I wonder if there is a cool 'chi' solution rather than a 'Go' solution, so I hope you don't mind me asking here..

Imagine you're building an image serving backend, where you can specify different parameters, such as:

`example.com/Jd8saD.jpg?width=420&height=320&fit=crop&rotate=90`

Each of these parameters (which could be included in any order) calls different functions to process the image. What would be the best way to go about doing this? Maybe use a single GET function like this:

```
function ImageGET(w http.ResponseWriter, r *http.Request) {
  if r.URL.Query().Get("width") != "" {
    // do something
  }
  if r.URL.Query().Get("height") != "" {
    // do something
  }
  if r.URL.Query().Get("crop") != "" {
    // do something
  }
  etc
}
```
?

By the way, is it even possible to check for this route? I know I could do:

`r.Get("/:image", ImageGET)`

but if I do that, then I assume there might be some conflicts with the other routes?

**Comment by pkieltyka** [comment]
Have a look at http://github.com/pressly/imgry

**Comment by edumucelli** [comment]
For those looking for the same thing few years later, you can use `if chi.URLParam(r, "width") != "" ...`

**Comment by suxor42** [comment]
@edumucelli This will always be true as `chi.URLParam(r, "key")` does not find query parameters. At least not in with version `github.com/go-chi/chi/v5 v5.0.0`

**Comment by ggicci** [comment]
If your request had many parameters, you may consider using a package like [ggicci/httpin](https://github.com/ggicci/httpin) to handle them. *httpin* is well integrated with chi,  see https://ggicci.github.io/httpin/integrations/gochi.

**Comment by IceflowRE** [comment]
> @edumucelli This will always be false as `chi.URLParam(r, "key")` does not find query parameters. At least not in with version `github.com/go-chi/chi/v5 v5.0.0`

Its quite a bad naming to be honest.
`chi.URLParam` returns the parameters from the url path, **not** from the query.
If you have `/foo/{id}` you can get the value of `id` with that function. For query parameters use `r.URL.Query().Get`.
According to the documentation
> URLParams are the stack of routeParams captured during the routing lifecycle across a stack of sub-routers.

**Comment by jcannell** [comment]
@IceflowRE thanks for this. Literally was going crazy.
