### ISSUE TITLE
Using FileServer with a middleware is inconvenient

### ISSUE THREAD

**Issue by djui** [pressly/chi#188]
Currently, when wanting to wrap `chi.FileServer` in a middleware such as BasicAuth one has to use one of two options, as the obvious one does not compile:

```go
r := chi.NewRouter()

// after `.With()` r is not a chi.Mux anymore but rather a chi.Router.
r.With(middleware.BasicAuth).FileServer("/foo", http.Dir("foo"))

// so instead:

r.With(middleware.BasicAuth).(*chi.Mux).FileServer("/foo", http.Dir("foo"))

// or

r.Route("/foo", func(r chi.Router) {
		r.Use(middleware.BasicAuth)
		r.(*chi.Mux).FileServer("/foo", http.Dir("foo"))
})

// or maybe something with `.Mount()` or `.Group()`.
```

Given https://github.com/pressly/chi/pull/183 this makes me wondering: Why do the following return `chi.Router` interfaces instead of the `*chi.Mux` type? All of them instantiate `*chi.Mux`.

- `chi.With()`
- `chi.Group()`
- `chi.Route()`

**Comment by djui** [comment]
Or should `chi.FileServer()` be added to the `chi.Router` interfaces, which, given that it this feature was likely added after the interface, would now break currently implementations.

**Comment by pkieltyka** [comment]
@djui `chi.FileServer()` is intended as a helper handler, not as something core. I took a slower step with it by first introducing it to the *Mux and not the Router.

**Comment by djui** [comment]
@pkieltyka Understood. And for the second half: What do you say about `chi.With()`, `chi.Group()`, `chi.Route()` returning `*chi.Mux`? That should be backwards compatible, right?

**Comment by pkieltyka** [comment]
@djui that isn't an option, better to add FileServer to Router. My priority is v3 roadmap
