### ISSUE TITLE
StripSlashes middleware prohibits FileServer

### ISSUE THREAD

**Issue by djui** [pressly/chi#189]
When using the `StripSlashes` middleware globally, `FileServer` never matches, as the trailing slash is removed from the request path, but is required by the router as `/*` is added by FileServer.

I understand that this could be fixed by mounting two separate sub-trees, one with the `StripSlashes` middleware and one without. But my "base router" that I provide to the developers already includes a set of sane middleware.

Is it possible to "undo" set middlewares for specific routes?

Is it possible to modify the find route in the node-tree to handle this corner case correctly or modify `StripSlashes` in any way to support not having to have trailing slashes?

**Comment by pkieltyka** [comment]
@djui I suggest you write your own middlewares as you require. chi is a router at the core with some optional middlewares. Working through all the combinations of middlewares is a whack-a-mole game

**Comment by pkieltyka** [comment]
chi only supports uses what is defined in the `Router` interface, otherwise it is a convenience / helper

**Comment by lrstanley** [comment]
For anyone else looking, there is an additional solution using `middleware.Maybe`, that could allow you to toggle middleware functionality based off path matching or similar. Mentioned it in another issue linked below, specifically for a debug/profiler endpoint, but would work similarly here:

https://github.com/go-chi/chi/issues/262#issuecomment-1200322044

Similarly, you could utilize another approach with `middleware.Maybe`, like checking for specific context values, or similar. Not perfect, but it works.
