### ISSUE TITLE
Use casbin as the authorization plugin for chi

### ISSUE THREAD

**Issue by hsluoyz** [pressly/chi#191]
Hi, I'm the author of [casbin](https://github.com/hsluoyz/casbin), a Go library for authorization based on access control policy. casbin supports multiple access control models like ACL, BLP, RBAC. The access control rules can be persisted into files, DB. In fact, It already has some successful stories on web frameworks like Beego, Tango here: https://github.com/hsluoyz/casbin#our-users. And a user of casbin asks me to add the support for chi [on the issues](https://github.com/hsluoyz/casbin/issues/5).

I saw chi has a middleware framework. So what do you think by adding casbin as an authorization middleware? Thanks!

**Comment by pkieltyka** [comment]
Hey Yang, I saw casbin and I think it's awesome! Yes I'd love to have a casabin middleware for chi - which really means a standard http middleware :)

**Comment by hsluoyz** [comment]
Already sent a PR here: https://github.com/pressly/chi/pull/192. Please advise:)

**Comment by pkieltyka** [comment]
Thanks :) I made a note about your community middleware in 898d761524954def9191dc8bea69191442581385
