### ISSUE TITLE
Chi pronunciation?

### ISSUE THREAD

**Issue by Bartuz** [pressly/chi#199]
Is it Chai (like JS framework/tea) or more like [greek letter χῖ](https://en.wikipedia.org/wiki/Chi_(letter)) (hi)

**Comment by pkieltyka** [comment]
hey @Bartuz I chose the word `chi` as a flow of energy at balance, from the word "qi" of Chinese culture.

phonetically it pronounced: ch-ee

thanks for asking :)

**Comment by Bartuz** [comment]
@pkieltyka nice! Much deeper and thoughtful than rubyist's "capybara", "puma", "unicorn" and "raptor"

**Comment by pkieltyka** [comment]
👍 thanks @Bartuz!

**Comment by lc-stevenzhang** [comment]
Glad to know the origin of this name, thanks!
By the way, here is the Chinese word of "chi":  气。
