### ISSUE TITLE
Question: Is it possible to get the executed Handler through middleware?

### ISSUE THREAD

**Issue by zbindenren** [pressly/chi#200]
Hi

Is it possible to get the current handler name somehow?

**Comment by pkieltyka** [comment]
See chi/docgen source

**Comment by zbindenren** [comment]
@pkieltyka thanks for the quick response. I know I can traverse the routes with chi.Routes(), but that is not what I want.

I am trying to get the route context inside a middleware. I tried it with:
```go
c := chi.RouteContext(r.Context())
fmt.Println(c.RoutePattern) 
```
I wrote a prometheus middleware for chi. Right now i takes as tag, statuscode, url and method.
```go
rw.Status()), r.Method, r.URL.Path
```
But with that approach I get a very large tag dimension (because every other option is another url), therefore I wanted to tag by the router pattern.

If it is not possible, no problem, I keep it the way I already have it.

**Comment by zemirco** [comment]
I've got the same problem. This is also related to https://github.com/go-chi/chi/pull/20. I'd like to add metrics to Prometheus https://prometheus.io/. It is on the way to becoming the standard monitoring solutions in cloud systems.

I'm currently using gorilla mux but would like to switch because of the way chi handles subrouters. I've written a custom middleware for mux to deal with monitoring.

```go
var requestDuration = prometheus.NewSummaryVec(prometheus.SummaryOpts{
	Name: "request_duration_milliseconds",
	Help: "The HTTP request latencies in milliseconds.",
}, []string{"method", "route", "status"})

func init() {
	prometheus.MustRegister(requestDuration)
}

func Instrument(router *mux.Router) func(http.Handler) http.Handler {
	return func(handler http.Handler) http.Handler {
		return http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
			m := httpsnoop.CaptureMetrics(handler, w, r)
			duration := float64(m.Duration / time.Millisecond)
			var routeMatch mux.RouteMatch
			route := r.URL.Path
			if router.Match(r, &routeMatch) {
				route, _ = routeMatch.Route.GetPathTemplate()
			}
			requestDuration.WithLabelValues(
				r.Method, route, strconv.Itoa(m.Code),
			).Observe(duration)
		})
	}
}
```

Currently there no easy way to achieve the same with chi. Any ideas or would you change your mind about adding this feature to the core library?

Cheers!

**Comment by pkieltyka** [comment]
@zemirco its possible already .. like so:

```go
func Instrument(next http.Handler) http.Handler {
	return http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		m := httpsnoop.CaptureMetrics(next, w, r)
		duration := float64(m.Duration / time.Millisecond)

		rctx := chi.RouteContext(r.Context())
		routePattern := strings.Join(rctx.RoutePatterns, "")
		routePattern = strings.Replace(routePattern, "/*/", "/", -1)

		requestDuration.WithLabelValues(
			r.Method, routePattern, strconv.Itoa(m.Code),
		).Observe(duration)

	})
}
```

please let me know how it goes .. yeay or nay

**Comment by pkieltyka** [comment]
I just added `rctx.RoutePattern()` to master as well.

**Comment by zemirco** [comment]
Looks promising! Cheers, will try.

**Comment by zemirco** [comment]
Just checked the source code cause I wanted to fix the comment indentation here https://github.com/go-chi/chi/blob/master/context.go#L79. How about adding `go vet` and `golint` to travis? There are several issues.

**Comment by zemirco** [comment]
Looks good! The solution works. I'm getting URLs like

```
/{username}/repositories/{repoID}
/{username}/followers/{followerID}
```

That's what I wanted.

One minor thing 😄 What I do not want for my route handlers is what I want for my file server. I'm getting `/public/*` for all my files.

Here is my setup

```go
r := chi.NewRouter()
r.Use(middleware.Instrument)
r.Method(http.MethodGet, "/public/*", http.StripPrefix("/public/", http.FileServer(http.Dir("public"))))
```

Is it possible to get more information about the files being served?

```go
/public/js/a.js
/public/js/b.js
/public/css/styles.css
```

**Comment by VojtechVitek** [comment]
Try to get the filename from `r.URL.Path` request path.

[http.FileServer()](https://golang.org/pkg/net/http/#FileServer) doesn't implement anything that would give you better hints on the route/file itself.

**Comment by pkieltyka** [comment]
@zemirco you'll have to build this yourself now :) we just offer support for core features. But what @VojtechVitek suggested makes sense.

**Comment by zemirco** [comment]
Ok I thought there is a built in solution since I'm getting the real file `/public/javascript/common.js` when I'm logging `chi.RouteContext(r.Context())`.

```
2017/07/31 21:54:47 middleware.go:112: /public/*
2017/07/31 21:54:47 middleware.go:110: &chi.Context{RoutePath:"", RoutePatterns:[]string{"/public/*"}, URLParams:chi.RouteParams{Keys:[]string{"*"}, Values:[]string{"javascript/common.js"}}, routePattern:"/public/*", routeParams:chi.RouteParams{Keys:[]string{"*"}, Values:[]string{"javascript/common.js"}}, methodNotAllowed:false}
```

I could totally build a simple check that tests for `/public/` and use `r.URL.Path` instead of the pattern.

👍

**Comment by pkieltyka** [comment]
@zemirco yea, in your fileserver specific middleware, just grab chi.URLParam(r, "*")
