### ISSUE TITLE
Custom handlers

### ISSUE THREAD

**Issue by carlqt** [pressly/chi#203]
Hi,

This is more of a question rather than an issue. From what I can see, the `GET, POST etc...` all takes a `string` and an `http.HandlerFunc`... Is there  a way to handle custom handlers? Like from this gist https://gist.github.com/elithrar/5aef354a54ba71a32e23

**Comment by pkieltyka** [comment]
hey @carlqt yes I will make this possible in v3 :) and I will provide an example as well

**Comment by VojtechVitek** [comment]
Imho, you can still use custom handlers's `http.HandlerFunc` explicitly:

```go
r := chi.NewRouter()
r.Get("/", appHandler{context, IndexHandler}.ServeHTTP)
```

**Comment by fr3fou** [comment]
Is this still the go-to way people do it?
