### ISSUE TITLE
r.Use(render.SetContentType(render.ContentTypeJSON)) from the 'rest' example

### ISSUE THREAD

**Issue by PlkMarudny** [pressly/chi#205]
What does the line above do? For sure it does not set heades; "Content-Type: text/plain; charset=utf-8" is what /panic route returns.

**Comment by pkieltyka** [comment]
@PlkMarudny it just hints to the render Responder that the content type should be JSON, the header is set right before the response body is sent back to the client, so long as you use `render.Respond()`

**Comment by PlkMarudny** [comment]
But when I use:
`r.Use(render.SetContentType(render.ContentTypeJSON))`
and
`r.Get("/ping", func(w http.ResponseWriter, r *http.Request) {
		w.Write([]byte("{ response : pong }"))
		render.Respond(w, r, nil)
	})`

The headers returned are:
`HTTP/1.1 200 OK
Date: Wed, 14 Jun 2017 05:51:18 GMT
Content-Length: 24
Content-Type: text/plain; charset=utf-8
`

**Comment by pkieltyka** [comment]
That's because when you call w.Write() it will send the header implicitly and the call to .Respond() will not then set the header. Remove the Write statement and it'll work.

**Comment by PlkMarudny** [comment]
Thank you, got this reading sources.
