### ISSUE TITLE
Subrouter hides parent routes

### ISSUE THREAD

**Issue by VojtechVitek** [pressly/chi#31]
```go
package main

import (
	"log"
	"net/http"

	"github.com/pressly/chi"
)

func main() {
	r := chi.NewRouter()

	// Parent route -- /foo
	r.Get("/foo", func(w http.ResponseWriter, r *http.Request) {
		log.Println("/foo")
	})

	// Subrouter -- defining /foo/bar
	r.Mount("/foo", subrouter())

	http.ListenAndServe(":3333", r)
}

func subrouter() http.Handler {
	r := chi.NewRouter()
	r.Get("/bar", func(w http.ResponseWriter, r *http.Request) {
		log.Println("/foo/bar")
	})
	return r
}
```

1) `$ curl -v localhost:3333/foo`
    
        > GET /foo HTTP/1.1
        < HTTP/1.1 404 Not Found
        Not Found
    
    The route **wasn't matched** -- seems like the subrouter hid it.

2) `$ curl -v localhost:3333/foo/`
    
        > GET /foo/ HTTP/1.1
        < HTTP/1.1 404 Not Found
        404 page not found
    
    Again.. but with **different body** -- different NotFound handler?

3) `$ curl -v localhost:3333/foo/bar`
    
        > GET /foo/bar HTTP/1.1
        < HTTP/1.1 200 OK
        /foo/bar
    
    OK

**Comment by pkieltyka** [comment]
What should it do?

Cuz the r.Mount() route is the same as the get request, and overwrites it. You should define the / route in the subrouter if it's using the same name, since that is its domain

**Comment by VojtechVitek** [comment]
Since I'm not overwriting the parent /foo path in the subrouter, I'd expect it to be matched and served anyways. Consider applying different middlewares for anonymous and auth'd routes from the parent router:

```go
func main() {
	r := chi.NewRouter()

	r.Group(func(r chi.Router) {
		r.Use(InjectAnonymousToken)
		
		r.Get("/", PublicRoutes())
	})

	r.Group(func(r chi.Router) {
		r.Use(TokenRefresh)
		r.Use(Authenticator)

		r.Mount("/", AuthRoutes())
	})

	http.ListenAndServe(":3333", r)
}
```

It would be nice to be able to "merge" those subroutes into a single matching route.

**Comment by VojtechVitek** [comment]
Another example:

1. THIS WORKS (subrouter first, .Get() merges into the routes):

```go
func main() {
    r := chi.NewRouter()

    // Public routes
    r.Group(func(r chi.Router) {
        r.Use(InjectAnonymousToken)

        r.Get("/", PublicRoutes())
    })

    // Auth'd routes
    r.Group(func(r chi.Router) {
        r.Use(TokenRefresh)
        r.Use(Authenticator)

        r.Mount("/", AuthRoutes())
    })

    http.ListenAndServe(":3333", r)
}
```

2) THIS DOESN'T WORK (subrouter second, it overrides the .Get() path w/o merge):

```go
func main() {
    r := chi.NewRouter()

    // Auth'd routes
    r.Group(func(r chi.Router) {
        r.Use(TokenRefresh)
        r.Use(Authenticator)

        r.Mount("/", AuthRoutes())
    })

    // Public routes
    r.Group(func(r chi.Router) {
        r.Use(InjectAnonymousToken)

        r.Get("/", PublicRoutes())
    })

    http.ListenAndServe(":3333", r)
}
```
