### ISSUE TITLE
[Feature Request]Static File serving

### ISSUE THREAD

**Issue by netsharec** [pressly/chi#35]
When I'm using `chi` for a project with [swagger-ui](https://github.com/swagger-api/swagger-ui), I feel it is not so convenient for serving static files. What about adding the static file serving feature like this:

```
func (mx *Mux) Static(path, root string) {
	fs := http.StripPrefix(path, http.FileServer(http.Dir(root)))
	mx.Get(path+"/*", func(w http.ResponseWriter, r *http.Request) {
		fs.ServeHTTP(w, r)
	})
}
```

**Comment by pkieltyka** [comment]
Hey @netsharec - yea, I can see how a shorthand would be nice, I'll see about adding it soon. But you can just as easily do..

```golang
r := chi.NewRouter()
//r.Use(..etc...)
r.Get("/", IndexEtc)
r.Mount("/files", http.FileServer(http.Dir("/files")))
```

**Comment by pkieltyka** [comment]
@netsharec I see what you mean. I'll add this function later today.

**Comment by fiorix** [comment]
Please allow it to take an http.FileSystem instead of directory so we can serve static file from memory. I often do that along with go-bindata.

**Comment by pkieltyka** [comment]
@fiorix good call

**Comment by pkieltyka** [comment]
Merged in #36 - see new `mux.FileServer(path string, root http.FileSystem)` method.. example usage: https://github.com/pressly/chi/blob/master/mux_test.go#L734-L743

**Comment by philippgille** [comment]
@pkieltyka: Is it correct that this functionality doesn't exist anymore, but instead you have to follow [this example](https://github.com/go-chi/chi/blob/master/_examples/fileserver/main.go)?

**Comment by pkieltyka** [comment]
yep, thats correct
