### ISSUE TITLE
How to handle "/" with trailing slashes in a mounted router?

### ISSUE THREAD

**Issue by mgenware** [pressly/chi#41]
Thanks for this great framework, currently I'm moving a project to chi, I want to handle all these URLs: `/blog`, `/blog/`, `/blog/list`.
I can do this in a plain router like this:
```go
// r is a Router variable
r.Get("/blog", blogHandler)
r.Get("/blog/", blogWithTrailingSlashHandler)
r.Get("/blog/list", blogListHandler)
```

but if I mount a nested router for `/blog`, how can I handle `/blog/`?
```go
// r is a Router variable
blogRouter := chi.NewRouter()
blogRouter.Get("/", blogHandler)
// this does not work
blogRouter.Get("//", blogWithTrailingSlashHandler)
blogRouter.Get("/list", blogListHandler)
r.Mount("/blog", blogRouter)
```

**Comment by mgenware** [comment]
Just solved this after a few minutes. this works fine now:
```go
// r is a Router variable
blogRouter := chi.NewRouter()
blogRouter.Get("/",  blogWithTrailingSlashHandler)
blogRouter.Get("/list", blogListHandler)
// mount this router for a URL with trailing slashes
r.Mount("/blog/", blogRouter)
r.Get("/blog", blogHandler)
```

**Comment by pkieltyka** [comment]
I also think you can r.Mount("/blog", blogRouter) and r.Get("/blog/", ...) where ... Can be a redirect to drop the trailing slash (which is best option IMO) or set it to the list handler

Let me know if that works

**Comment by mgenware** [comment]
@pkieltyka Yes, it works.
