### ISSUE TITLE
404 not found when expecting 405 method not allowed

### ISSUE THREAD

**Issue by mrcpvn** [pressly/chi#44]
A request sent to an existing resource without an handler for that method should return http 405.
If I understand correctly this should be the behaviour in
        
    // Check if method is supported by chi
	method, ok := methodMap[r.Method]
	if !ok {
		methodNotAllowedHandler(ctx, w, r)
		return
	}

but I am getting always an http 404 error. 
methodMap is initialized at startup and a method will be always found in the map, after that an handler will not be found and we finish in the handler not found case. 

Maybe this control has been implemented to manage unexpected http methods that the router will not be able to handle in every case. Am I right?

**Comment by pkieltyka** [comment]
@mrcpvn yea, with 404, it lets you mount the NotFound() handler and response to the user. I'm open to just returning a 405, but then theres no control to the app developer here. I'll think about this some more for chi v2

**Comment by pkieltyka** [comment]
@mrcpvn how come you've closed it...? have you solved this in a different way?

**Comment by mrcpvn** [comment]
I closed the issue because the same feature can be created with a middleware.
From my point of view this is not a bug if the methodNotAllowedHandler is used to handle an http method that is not expected from the chi.Router.

**Comment by pkieltyka** [comment]
makes sense, thanks for the followup!
