### ISSUE TITLE
Track routing pattern for each request

### ISSUE THREAD

**Issue by pkieltyka** [pressly/chi#45]
..useful for instrumentation middleware

**Comment by pkieltyka** [comment]
Done in v2 branch

**Comment by lwc** [comment]
🎉 this pretty much satisfies my requirement here: https://github.com/pressly/chi/issues/43#issuecomment-223188687 🎉 👍

**Comment by pkieltyka** [comment]
Awesome!! Let me know how you use the tracking patterns to achieve what you're planning

**Comment by srinathilabs** [comment]
How the tracking is done? Where can I see the documentation?
