### ISSUE TITLE
use a color library for middleware

### ISSUE THREAD

**Issue by nhooyr** [pressly/chi#50]
https://github.com/nhooyr/color

It fully supports terminfo, but not windows.

**Comment by pkieltyka** [comment]
@nhooyr thanks for the note, but, whats the use case? I'd also like to avoid any external dependencies for any of chi's packages/subpackages

the middleware.Logger already has some nice colors.

**Comment by nhooyr** [comment]
@pkieltyka well it fully supports terminfo so older terminals will work. You won't need to hardcode all of the color escapes.

**Comment by pkieltyka** [comment]
right on, it looks like a very nice library, but I dont want to introduce external libraries to the core. perhaps, we could make a separate middleware logger outside of chi that uses plain-jane "context" for go1.7, using your lib, and it will _just work_ in chi

**Comment by pkieltyka** [comment]
or if you want to submit an to https://github.com/pressly/chi/blob/master/middleware/terminal.go to improve support, that would be awesome too
