### ISSUE TITLE
Panic when middleware stack is set, and r.Use() is called

### ISSUE THREAD

**Issue by pkieltyka** [pressly/chi#65]
Prevents misuse as in, https://github.com/pressly/chi/pull/64/files

**Comment by VojtechVitek** [comment]
test case:
https://github.com/pressly/chi/pull/64/commits/baa2aaa23447b035875e066e7e7bdcdc9838e183

**Comment by pkieltyka** [comment]
done in ffaa9a31d8e31fff720276885048d779ff0ccfaf
