### ISSUE TITLE
How to get params without route context?

### ISSUE THREAD

**Issue by gpopovic** [pressly/chi#76]
Is it possible to get param from the handler without route context?

When i'm testing handler, i need to be able to retrieve params with chi.URLParam(), but when i try to do it outside router, i'm getting panic

**Comment by pkieltyka** [comment]
@gpopovic can you show me the test code for that handler?

it's possible to go about it a few ways, but if you're testing just a single handler that is trying to fetch URLParams from a request, then you need to make sure the URLParams object is available on the request chain. Have a look at https://github.com/pressly/chi/blob/master/mux_test.go#L810-L829

**Comment by gpopovic** [comment]
@pkieltyka exactly what i needed. Thanks

**Comment by christopherdiehl** [comment]
@pkieltyka can you show an example? Didn't follow the mux_test.go

Thank you!

**Comment by soedar** [comment]
I've recently ran into the same issue. For posterity, this should work: 
```golang
w := httptest.NewRecorder()
r := httptest.NewRequest("GET", "/", nil)

rctx := chi.NewRouteContext()
rctx.URLParams.Add("key", "value")

r = r.WithContext(context.WithValue(r.Context(), chi.RouteCtxKey, rctx))

handler := func(w http.ResponseWriter, r *http.Request) {
	key := chi.URLParam(r, "key") // "value"
}
handler(w, r)
```

Adapted from: https://github.com/go-chi/chi/blob/91a3777c41c3d3493a446f690b572d93a76cba73/mux_test.go#L1143-L1145
