### ISSUE TITLE
Ability to join routers.

### ISSUE THREAD

**Issue by gpopovic** [pressly/chi#77]
It could be useful to be able to join multiple routers (but not forcing the second router to have a specific path).

My handlers is split into multiple packages and each package has NewRouter() function returning chi.Router.

The idea is for my main application, to import packages and then do

mainRouter.Join(package1.NewRouter())
mainRouter.Join(package2.NewRouter())

I'm currently doing it this way, but it's not that elegant

package1.AddRoutes(mainRouter)
package2.AddRoutes(mainRouter)

Mount is not useful, because it forces to pick a specific path for router.

**Comment by pkieltyka** [comment]
@gpopovic hey there, hmmm.. did you read the README or look at the examples? A huge design goal of chi is to join routers together, via `r.Mount` .. of course it can do this.

Please keep the issues about bugs and not Q&A. I will be working on some better docs with examples, but its all there if you look closely and learn how to use the framework.

**Comment by gpopovic** [comment]
@pkieltyka
