### ISSUE TITLE
Ability to set the base context

### ISSUE THREAD

**Issue by cyx** [pressly/chi#90]
I'm not sure there's a facility for this already, but after searching through the code and docs, there doesn't seem to be a way to do it without making a middleware.

Basically the usecase is like:

```go
ctx := context.WithValue(context.Background(), "foo", "bar")

mux := chi.NewMux()
mux.SetContext(ctx) // or could be in the constructor, or a functional option thing?
```

In any case the underlying goal is to just easily set the base context. Let me know if this makes sense.

**Comment by pkieltyka** [comment]
@cyx yea I've gone back and forth with this one myself. I've implemented it, then removed it, then thought perhaps we should bring it back.

can you describe your use case for a base context? what would you use it for?

**Comment by VojtechVitek** [comment]
I was thinking about custom context types:

```go
ctx := &MyCustomAppContext{} // implements context.Context interface
router := chi.NewRouter(ctx)
```

```go
func Handler(w http.ResponseWriter, r *http.Request) {
  ctx := r.Context().(*MyCustomAppContext)

  // I can use custom methods/helpers defined on the *MyCustomAppContext type now..
  // this means... saving a lot of boiler plate and type conversions 
  sessionUser := ctx.SessionUser()

  session := ctx.Session() // instead of session, ok := ctx.Value("session").(*Session)

  db := ctx.DBSession() // DB connection assigned from a middleware?

  w.Write([]byte("yay"))
}
```

**Comment by cyx** [comment]
For our usecase, the most important part is cancellation.

```go
        ctx, cancel := context.WithCancel(context.Background())

        graceful.AddSignal(syscall.SIGTERM)
        graceful.PostHook(cancel)

        // more code here that adds on to context.
```

FWIW we were originally using github.com/guregu/kami. We definitely love a working PR we have moving to chi, and this is the only piece that felt weird to me TBH.

**Comment by pkieltyka** [comment]
@cyx that isn't actually a reliable solution to a graceful shutdown of your servers. A cancelation signal will cancel all in-process goroutines. What is actually necessary is a signal on the context that tells the listeners to stop any further processing, but to finish up their work. See https://github.com/pressly/chi/issues/58

**Comment by pkieltyka** [comment]
@cyx let me know if you get any success or some other ideas on how to approach it though

**Comment by cyx** [comment]
@pkieltyka do you sit in any irc / slack channel? Would be interested to talk about this in detail.

**Comment by pkieltyka** [comment]
@cyx id love to get into it, but I'm under a pile of work onboarding a bunch of customers this week

**Comment by pkieltyka** [comment]
btw, here is a PR to add this functionality https://github.com/pressly/chi/pull/92

I'll be adding a _examples/graceful example too to this PR that uses the new github.com/goware/valve package to manage graceful shutdowns, utilizing a base context

**Comment by pkieltyka** [comment]
done in a526d0cd90dc44b65a6cbde23b0bf34718eddc59
